### ISSUE TITLE
Installation Issue on Debian

### ISSUE THREAD

**Issue by Yashvendra** [rsmusllp/king-phisher#441]
## Issue Description
I experience an issue while installing King-phisher. It throws `failed to install the pipenv enviroment`.

## Reproduction Steps
1. sudo ./install.sh
2. Select distribution then Y, Y.

## Environment Details

Host OS: deepin 5.3.15-6apricot (2020-04-13) x86_64 GNU/Linux
King Phisher Version: KingPhisherServer Version: 1.16.0-beta (rev: 2181ba508d5f)

## Error Details / Stack Trace

```
✔ Successfully created virtual environment! 
Virtualenv location: /opt/king-phisher/.venv
Virtualenv already exists!
Removing existing virtualenv…
Creating a virtualenv for this project…
Pipfile: /opt/king-phisher/Pipfile
Using /usr/bin/python3.7m (3.7.3) to create virtualenv…
⠼ Creating virtual environment...Using base prefix '/usr'
New python executable in /opt/king-phisher/.venv/bin/python3.7m
Also creating executable in /opt/king-phisher/.venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Running virtualenv with interpreter /usr/bin/python3.7m

✔ Successfully created virtual environment! 
Virtualenv location: /opt/king-phisher/.venv
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Building requirements...
Resolving dependencies...
⠙ Locking..✔ Success! 
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
⠧ Locking..Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/cli/command.py", line 252, in install
    site_packages=state.site_packages
  File "/usr/local/lib/python3.7/dist-packages/pipenv/core.py", line 2063, in do_install
    keep_outdated=keep_outdated
  File "/usr/local/lib/python3.7/dist-packages/pipenv/core.py", line 1303, in do_init
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.7/dist-packages/pipenv/core.py", line 1113, in do_lock
    keep_outdated=keep_outdated
  File "/usr/local/lib/python3.7/dist-packages/pipenv/utils.py", line 1323, in venv_resolve_deps
    c = resolve(cmd, sp)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/utils.py", line 1136, in resolve
    result = c.expect(u"\n", timeout=environments.PIPENV_INSTALL_TIMEOUT)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/delegator.py", line 215, in expect
    self.subprocess.expect(pattern=pattern, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f33effb55c0>
searcher: searcher_re:
    0: re.compile('\n')
<pexpect.popen_spawn.PopenSpawn object at 0x7f33effb55c0>
searcher: searcher_re:
    0: re.compile('\n')
pipenv encountered the following error:
ERROR    failed to install the pipenv environment
INFO: Installing the client desktop application file
INFO: Updating the GTK icon cache
gtk-update-icon-cache: Cache file created successfully.
INFO: Configuring the PostgreSQL server
INFO: PostgreSQL configuration file found at /etc/postgresql/11/main/pg_hba.conf
WARNING: The PostgreSQL king_phisher user already exists! The password will need
WARNING: to be manually updated to match the one automatically generated by this
WARNING: installation script (by using the ALTER ROLE PostgreSQL command) or
WARNING: restored from a previously backed up server configuration file.
INFO: Installing the King Phisher systemd service file in /lib/systemd/system/
INFO: Starting the King Phisher service
Job for king-phisher.service failed because a timeout was exceeded.
See "systemctl status king-phisher.service" and "journalctl -xe" for details.
--------------------------------------------------------------------------------
INFO: You can start the King Phisher client with the following command:
/opt/king-phisher/KingPhisher

```

**Comment by zeroSteiner** [comment]
Looks like the dependencies have failed to install. Does the server have a functional internet connection? What happens if you run "sudo pipenv install"?

**Comment by zeroSteiner** [comment]
Actually it looks like you're not using Debian but rather deepin which is a fork of Debian? Is that right?

**Comment by Yashvendra** [comment]
Yes, I am using Deepin. 
I think the issue is resolved now, after doing `sudo pipenv install` one installation error came in indeed.
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/23001311/92596129-f5d25180-f2c2-11ea-91b3-baffd4fc8350.PNG">
However, when I started the KingPhisherServer with the default server_config.yml, it started successfully then later running the client also worked.

**Comment by zeroSteiner** [comment]
Okay that's good. That issue you're seeing though is alright, at the end it says it'll try again and that's what it does so you can safely ignore it. Sometimes pipenv fails to install a package on the first try due to missing dependencies that are installed later IIRC.
