### ISSUE TITLE
Can't launch King-Phisher

### ISSUE THREAD

**Issue by bastardacademic** [rsmusllp/king-phisher#483]
When I try to launch King-Phisher, I get this:

/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Loading .env environment variables...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/king-phisher/king_phisher/client/__main__.py", line 48, in <module>
    from king_phisher.client import application
  File "/opt/king-phisher/king_phisher/client/application.py", line 59, in <module>
    from king_phisher.client import dialogs
  File "/opt/king-phisher/king_phisher/client/dialogs/__init__.py", line 37, in <module>
    from .configuration import *
  File "/opt/king-phisher/king_phisher/client/dialogs/configuration.py", line 41, in <module>
    from king_phisher.client import graphs
  File "/opt/king-phisher/king_phisher/client/graphs.py", line 52, in <module>
    import matplotlib
  File "/opt/king-phisher/.venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 192, in <module>
    if not compare_versions(six.__version__, '1.10'):
  File "/opt/king-phisher/.venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 179, in compare_versions
    a = distutils.version.LooseVersion(a)
AttributeError: module 'distutils' has no attribute 'version'

## Environment Details

Host OS: Ubuntu 20.04.4 GNOME
King Phisher Version: current

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by cahocachi** [comment]
Having the same issue, running in a fresh Ubuntu 20.04 as well.

**Comment by Hosted-EU** [comment]
There’s a new Phishing Tool Out There!!
It’s able to capture cookies to bypass 2FA ✅

Watch Video On How It Works : https://www.youtube.com/watch?v=Bgu4JtCwtX0
