### ISSUE TITLE
No such file or directory 

### ISSUE THREAD

**Issue by Doujinx** [rsmusllp/king-phisher#499]
`/home/kali/Programs/king-phisher/KingPhisher

WARNING  no pre-existing pipenv environment was found, installing it now
pipenv encountered the following error:
ERROR    failed to install the pipenv environment
ERROR    failed to remove the incomplete .venv directory
Traceback (most recent call last):
  File "/home/kali/Programs/king-phisher/king_phisher/startup.py", line 188, in pipenv_entry
    shutil.rmtree(os.path.join(target_directory, '.venv'))
  File "/usr/lib/python3.11/shutil.py", line 722, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.11/shutil.py", line 720, in rmtree
    orig_st = os.lstat(path, dir_fd=dir_fd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kali/Programs/king-phisher/.venv'`

**Comment by Doujinx** [comment]
I fixed it, but when i run ./KingPhisher i got that : 

Loading .env environment variables...
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/kali/Programs/king-phisher/king_phisher/client/__init__.py", line 35, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by leonjensentan** [comment]
> I get that issue with venv, there is no directory, maybe you was have the same issue ?
> 
> `/home/kali/Programs/king-phisher/KingPhisher
> 
> WARNING no pre-existing pipenv environment was found, installing it now pipenv encountered the following error: ERROR failed to install the pipenv environment ERROR failed to remove the incomplete .venv directory Traceback (most recent call last): File "/home/kali/Programs/king-phisher/king_phisher/startup.py", line 188, in pipenv_entry shutil.rmtree(os.path.join(target_directory, '.venv')) File "/usr/lib/python3.11/shutil.py", line 722, in rmtree onerror(os.lstat, path, sys.exc_info()) File "/usr/lib/python3.11/shutil.py", line 720, in rmtree orig_st = os.lstat(path, dir_fd=dir_fd) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: '/home/kali/Programs/king-phisher/.venv'`

How did you solve this issue?

**Comment by Hosted-EU** [comment]
There’s a new Phishing Tool Out There!!
It’s able to capture cookies to bypass 2FA 🔥🔥🔥

Watch Video On How It Works : https://www.youtube.com/watch?v=Bgu4JtCwtX0
