### ISSUE TITLE
ImportError undefined Symbol _PyUnicode_AsStringAndSize

### ISSUE THREAD

**Issue by charlyrock** [rsmusllp/king-phisher#510]
## Issue Description
I experience an issue when I installed king-phisher. 
I installed it, configured pipenv and after it runs and installed king-phisher and try to start /opt/king-phisher/KingPhisher I get the a error message, that it is a undefined symbol. 

## Reproduction Steps
1. Install King Phisher
2. /opt/king-phisher/KingPhisher
3. I must update some packages in Pipfile, because pipenv doesn´t run. I updated the package: PyYAML, Cython, Numpy.
4. I tried different versions of Cython, because my google search give me some informations that 0.29.22 or 0.29.21 shouldn´t have the problem with the icon. But in every version I get the failure

## Environment Details

Host OS: Ubuntu 22.04 
King Phisher Version: latest version

## Error Details / Stack Trace

```
Loading .env environment variables...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/opt/king-phisher/king_phisher/client/__init__.py", line 35, in <module>
    import gi
  File "/opt/king-phisher/.venv/lib/python3.10/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /opt/king-phisher/.venv/lib/python3.10/site-packages/gi/_gi.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_AsStringAndSize
```

**Comment by charlyrock** [comment]
I delete the file. Then it works
